# Generated by Django 4.2.20 on 2025-03-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=20)),
                ('chassis_number', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('registration_certificate', models.FileField(upload_to='registration_certificates/')),
            ],
        ),
    ]
