# Generated by Django 4.2.20 on 2025-03-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_remove_bus_datetime_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.TextField()),
                ('route_key', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
