# Generated by Django 4.2.20 on 2025-04-02 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_add_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_route',
            name='route_key',
        ),
        migrations.AddField(
            model_name='add_route',
            name='from_stop',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_route',
            name='to_stop',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
