# Generated by Django 4.2.20 on 2025-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_remove_add_route_route_key_add_route_from_stop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('ticket_code', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
