# Generated by Django 4.2.20 on 2025-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_ticketcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcode',
            name='Name',
            field=models.CharField(default='no user', max_length=40),
        ),
    ]
