# Generated by Django 4.2.20 on 2025-04-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_remove_ticketcode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcode',
            name='travel',
            field=models.IntegerField(default=1),
        ),
    ]
