# Generated by Django 4.2.20 on 2025-04-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0013_ticketcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcode',
            name='bus_id',
            field=models.TextField(default='TN00V000'),
        ),
    ]
