# Generated by Django 4.2.20 on 2025-04-07 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0014_ticketcode_bus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('travel', models.IntegerField()),
                ('ticket_code', models.CharField(max_length=10)),
                ('bus_id', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.passenger')),
            ],
        ),
    ]
