# Generated by Django 4.2.20 on 2025-04-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0015_passengerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerhistory',
            name='user',
            field=models.TextField(default='user'),
        ),
    ]
