# Generated by Django 4.2.20 on 2025-04-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0016_alter_passengerhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerhistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='passengerhistory',
            name='time',
        ),
        migrations.AddField(
            model_name='passengerhistory',
            name='created_at',
            field=models.TextField(default='not apply'),
        ),
        migrations.AddField(
            model_name='passengerhistory',
            name='moved_at',
            field=models.TextField(default='0:0'),
        ),
    ]
